const router = require('express').Router();
const { requireAuth } = require('../middleware/auth');
const { askAssistant, chatWithPersona, generateSuggestions, generateWizardQuestions, PERSONAS } = require('../services/knowledgeAgent');

// ── POST /assistant/ask ──────────────────────────────────────────────────
// "Ask HavenIQ" — answers a student's roommate / cohabitation question via
// the knowledge agent. One Anthropic call per question; the service is
// best-effort and never throws, so this route always returns a usable
// answer (a graceful fallback if the AI is unreachable).
router.post('/ask', requireAuth, async (req, res) => {
  try {
    const question = String((req.body && req.body.question) || '').trim();
    if (!question) return res.status(400).json({ error: 'question is required' });

    const { answer, source } = await askAssistant(question, '', req.user.id);
    res.json({ answer, source });
  } catch (err) {
    console.error('[assistant/ask] failed:', err.message);
    res.status(500).json({ error: 'Assistant is unavailable right now.' });
  }
});

// ── POST /assistant/chat ─────────────────────────────────────────────────
// Multi-turn chat with one of HavenIQ's purpose-built personas
// (advisor, mediator, profile_writer, negotiator, conflict_coach,
// interview_coach, financial_advisor). System prompts live server-side so
// users can't override them — they only pick a persona key.
//
// Body: { persona: string, messages: [{role, content}], context?: string }
router.post('/chat', requireAuth, async (req, res) => {
  try {
    const { persona, messages, context } = req.body || {};
    if (!persona || typeof persona !== 'string') {
      return res.status(400).json({ error: 'persona is required' });
    }
    if (!PERSONAS[persona]) {
      return res.status(400).json({ error: `unknown persona "${persona}"` });
    }
    if (!Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: 'messages must be a non-empty array' });
    }
    // Cap the context blob — it's user-supplied profile data, not arbitrary
    // text, but defense-in-depth against a runaway prompt size.
    const ctx = typeof context === 'string' ? context.slice(0, 4000) : '';

    const { answer, source } = await chatWithPersona(persona, messages, ctx, req.user.id);
    res.json({ answer, source });
  } catch (err) {
    console.error('[assistant/chat] failed:', err.message);
    res.status(500).json({ error: 'Assistant is unavailable right now.' });
  }
});

// ── POST /assistant/suggestions ───────────────────────────────────────────
// Returns 4-6 personalized question starters for a given persona,
// generated by Claude using the user's context (matches, profile, etc.).
// Replaces every hardcoded chip list in the app.
//
// Body: { persona: string, context?: string }
router.post('/suggestions', requireAuth, async (req, res) => {
  try {
    const { persona, context } = req.body || {};
    if (!persona || typeof persona !== 'string') {
      return res.status(400).json({ error: 'persona is required' });
    }
    if (!PERSONAS[persona]) {
      return res.status(400).json({ error: `unknown persona "${persona}"` });
    }
    const ctx = typeof context === 'string' ? context.slice(0, 4000) : '';
    const { suggestions } = await generateSuggestions(persona, ctx);
    res.json({ suggestions });
  } catch (err) {
    console.error('[assistant/suggestions] failed:', err.message);
    res.status(500).json({ error: 'Could not generate suggestions.' });
  }
});

// ── POST /assistant/wizard ────────────────────────────────────────────────
// Generates a wizard's question set + options dynamically. Used to
// replace hardcoded MCQ forms on profile-writer, mediator, etc.
//
// Body: { persona, kind, questionCount?, optionsPerQuestion?, context? }
// Returns: { questions: [{ text, options }] }
router.post('/wizard', requireAuth, async (req, res) => {
  try {
    const { persona, kind, questionCount, optionsPerQuestion, context } = req.body || {};
    if (!persona || typeof persona !== 'string' || !PERSONAS[persona]) {
      return res.status(400).json({ error: 'valid persona is required' });
    }
    if (!kind || typeof kind !== 'string') {
      return res.status(400).json({ error: 'kind is required' });
    }
    const qc  = Math.min(Math.max(parseInt(questionCount, 10) || 5, 1), 10);
    const opc = Math.min(Math.max(parseInt(optionsPerQuestion, 10) || 4, 2), 6);
    const ctx = typeof context === 'string' ? context.slice(0, 4000) : '';
    const { questions } = await generateWizardQuestions({
      persona, kind, questionCount: qc, optionsPerQuestion: opc, context: ctx,
    });
    res.json({ questions });
  } catch (err) {
    console.error('[assistant/wizard] failed:', err.message);
    res.status(500).json({ error: 'Could not generate wizard.' });
  }
});

module.exports = router;
